(function () {
  const paletteRoutes = [
    {
      id: "RIU-001",
      name: "Convergence & Scope Clarification",
      keywords: ["clarify", "unclear", "scope", "direction", "where do i start", "confused", "alignment"],
      agent: "Yuty (Narrative) -> Rex (Architecture)",
      artifact: "Convergence Brief",
      action: "Define target outcome, non-goals, and first success metric."
    },
    {
      id: "RIU-014",
      name: "Business Planning & Positioning",
      keywords: ["business plan", "strategy", "positioning", "roadmap", "model", "offer", "pricing"],
      agent: "Rex (Architecture) + Yuty (Narrative)",
      artifact: "Operating Plan v1",
      action: "Build a one-page strategy, priorities, and 30-day execution plan."
    },
    {
      id: "RIU-028",
      name: "Market Signal & Brand Narrative",
      keywords: ["brand", "podcast", "drop", "campaign", "marketing", "audience", "content", "story"],
      agent: "Argy (Research) -> Yuty (Narrative)",
      artifact: "Go-To-Market Brief",
      action: "Map competitors, audience signals, and narrative hooks."
    },
    {
      id: "RIU-039",
      name: "Funding & Grants",
      keywords: ["grant", "funding", "loan", "application", "capital", "subsidy", "government"],
      agent: "Argy (Research) + Theri (Build)",
      artifact: "Funding Pipeline + Draft Applications",
      action: "Generate funding list, eligibility matrix, and first application draft."
    },
    {
      id: "RIU-062",
      name: "Build & Implementation",
      keywords: ["build", "website", "app", "automation", "system", "implement", "launch"],
      agent: "Theri (Build) with Rex (Architecture)",
      artifact: "Implementation Spec + Build Tasks",
      action: "Convert plan into build tickets and delivery sequence."
    },
    {
      id: "RIU-073",
      name: "Debug & Recovery",
      keywords: ["bug", "error", "broken", "issue", "fix", "not working", "failure"],
      agent: "Raptor (Debug)",
      artifact: "Root-Cause + Fix Plan",
      action: "Identify failure point and define minimal corrective action."
    }
  ];

  function scoreRoute(input, route) {
    const text = input.toLowerCase();
    let score = 0;
    for (const keyword of route.keywords) {
      if (text.includes(keyword)) {
        score += keyword.split(" ").length > 1 ? 2 : 1;
      }
    }
    return score;
  }

  function chooseRoute(payload) {
    const fullText = [payload.question, payload.context, payload.outcome, payload.constraints].join(" ");
    let best = paletteRoutes[0];
    let bestScore = -1;

    for (const route of paletteRoutes) {
      const s = scoreRoute(fullText, route);
      if (s > bestScore) {
        best = route;
        bestScore = s;
      }
    }

    if (bestScore <= 0) {
      return {
        id: "RIU-001",
        name: "Convergence & Scope Clarification",
        agent: "Yuty (Narrative) -> Rex (Architecture)",
        artifact: "Convergence Brief",
        action: "Clarify objective, constraints, and first measurable output.",
        why: "No strong keyword match. Defaulting to convergence-first routing."
      };
    }

    return {
      ...best,
      why: "Matched route signals in your question and context."
    };
  }

  function buildBrief(payload, route) {
    const date = new Date().toISOString().slice(0, 10);
    return [
      "# MissionCanvas Action Brief",
      "",
      `Date: ${date}`,
      `Route: ${route.id} - ${route.name}`,
      `Primary Agent: ${route.agent}`,
      "",
      "## Input",
      `Question: ${payload.question || "N/A"}`,
      `Context: ${payload.context || "N/A"}`,
      `Desired Outcome: ${payload.outcome || "N/A"}`,
      `Constraints: ${payload.constraints || "N/A"}`,
      "",
      "## Immediate Plan",
      `Why this route: ${route.why}`,
      `Next artifact: ${route.artifact}`,
      `Immediate action: ${route.action}`,
      "",
      "## Convergence Checks",
      "- Is the target outcome explicit and measurable?",
      "- Are non-goals defined?",
      "- Is this a ONE-WAY or TWO-WAY decision?",
      "- What is the first deliverable in 24-72 hours?",
      "",
      "Generated by MissionCanvas (Palette router test)."
    ].join("\n");
  }

  function initAskForm() {
    const form = document.getElementById("askForm");
    if (!form) return;

    const result = document.getElementById("askResult");
    const rRiu = document.getElementById("rRiu");
    const rAgent = document.getElementById("rAgent");
    const rWhy = document.getElementById("rWhy");
    const rArtifact = document.getElementById("rArtifact");
    const rAction = document.getElementById("rAction");
    const briefOutput = document.getElementById("briefOutput");
    const copyBtn = document.getElementById("copyBrief");
    const emailBtn = document.getElementById("emailBrief");

    let currentBrief = "";

    form.addEventListener("submit", function (e) {
      e.preventDefault();
      const data = new FormData(form);
      const payload = {
        question: (data.get("question") || "").toString().trim(),
        context: (data.get("context") || "").toString().trim(),
        outcome: (data.get("outcome") || "").toString().trim(),
        constraints: (data.get("constraints") || "").toString().trim()
      };

      const route = chooseRoute(payload);
      currentBrief = buildBrief(payload, route);

      rRiu.textContent = `${route.id} - ${route.name}`;
      rAgent.textContent = route.agent;
      rWhy.textContent = route.why;
      rArtifact.textContent = route.artifact;
      rAction.textContent = route.action;
      briefOutput.value = currentBrief;

      result.classList.remove("hidden");
      result.scrollIntoView({ behavior: "smooth", block: "start" });
    });

    copyBtn.addEventListener("click", async function () {
      if (!currentBrief) return;
      try {
        await navigator.clipboard.writeText(currentBrief);
        copyBtn.textContent = "Copied";
        setTimeout(function () { copyBtn.textContent = "Copy Brief"; }, 1200);
      } catch (_err) {
        copyBtn.textContent = "Copy failed";
      }
    });

    emailBtn.addEventListener("click", function () {
      if (!currentBrief) return;
      const subject = encodeURIComponent("MissionCanvas Routed Brief");
      const body = encodeURIComponent(currentBrief);
      window.location.href = `mailto:hello@missioncanvas.ai?subject=${subject}&body=${body}`;
    });
  }

  function initHeroAsk() {
    const form = document.getElementById("heroAskForm");
    const heroInput = document.getElementById("heroQuestion");
    if (!form || !heroInput) return;

    const tags = document.querySelectorAll(".tag[data-q]");
    tags.forEach(function (tag) {
      tag.addEventListener("click", function () {
        heroInput.value = tag.getAttribute("data-q") || "";
        heroInput.focus();
      });
    });

    form.addEventListener("submit", function (e) {
      e.preventDefault();
      const askQuestion = document.getElementById("question");
      if (askQuestion) {
        askQuestion.value = heroInput.value.trim();
      }
      const askSection = document.getElementById("ask");
      if (askSection) {
        askSection.scrollIntoView({ behavior: "smooth", block: "start" });
      }
    });
  }

  function initWaitlist() {
    const form = document.getElementById("waitlistForm");
    if (!form) return;

    form.addEventListener("submit", function (e) {
      e.preventDefault();
      const data = new FormData(form);
      const name = data.get("name") || "";
      const email = data.get("email") || "";
      const goal = data.get("goal") || "";

      const subject = encodeURIComponent("MissionCanvas Waitlist Request - " + name);
      const body = encodeURIComponent(
        "Name: " + name + "\n" +
        "Email: " + email + "\n\n" +
        "Goal:\n" + goal + "\n"
      );

      window.location.href = "mailto:hello@missioncanvas.ai?subject=" + subject + "&body=" + body;
    });
  }

  initAskForm();
  initHeroAsk();
  initWaitlist();
})();
