id: gap-ai-strategy
name: Gap Inc. AI Strategy & Enterprise Enablement
description: Multi-phase engagement producing CFO-ready AI strategy with FDE model, hybrid governance, and 3-year roadmap

phases:
  - id: phase-0
    name: Convergence Brief
    agent: Human + Kiro
    inputs: [Job description, Mical's background, Gap context]
    outputs: [gap_convergence_brief.md, decisions.md]
    quality_gate: All 5 convergence questions answered, ONE-WAY DOOR decisions flagged
    decisions: [FDE model positioning, retail gap framing, AI benefits framework, leadership alignment, platform philosophy]
    memory_updates: [Success criteria, positioning, priority gaps]
    approval: human
    
  - id: phase-1
    name: Argy Research (5 cycles)
    agent: Argy
    parallelizable: [cycle-1, cycle-2, cycle-4, cycle-5 independent; cycle-3 sequential]
    inputs: [Convergence brief, Perplexity API]
    outputs: [gap_argy_roi_research.md, gap_argy_risk_governance_research.md, gap_argy_operating_model_research.md, gap_argy_fde_model_research.md, gap_argy_current_state_research.md, gap_argy_retail_landscape_research.md]
    quality_gate: All research cited with sources, retail comparables included, FDE model validated
    decisions: []
    memory_updates: [ROI frameworks, governance models, FDE team structure, Gap current state, retail benchmarks]
    approval: auto
    
  - id: phase-2
    name: Rex Strategic Framework
    agent: Rex
    inputs: [All Argy research, convergence brief]
    outputs: [gap_rex_strategic_framework.md, gap_retail_ai_strategy_matrix.md]
    quality_gate: AI readiness assessment complete, use case prioritization matrix with scores, platform decision justified, governance model defined, roadmap with milestones
    decisions: [Platform selection (Google Cloud), Governance model (hybrid), Operations-first sequencing]
    memory_updates: [Team size (10-11 FTE), Year 1-3 budget, use case priorities]
    approval: human
    
  - id: phase-3
    name: Rex Use Case Deep Dives
    agent: Rex
    parallelizable: [3 pilots independent]
    inputs: [Strategic framework, use case prioritization]
    outputs: [gap_rex_use_case_deep_dives.md]
    quality_gate: Each pilot has problem statement, AI approach, ROI model, risk assessment, AWS analog
    decisions: []
    memory_updates: [Pilot costs ($185K), pilot ROI ranges, payback period]
    approval: auto
    
  - id: phase-4
    name: Adoption & Change Management
    agent: Yuty + Theri
    inputs: [Use case deep dives, Mical's AWS proof point]
    outputs: [gap_adoption_framework.md]
    quality_gate: 5 personas defined, 38 recipes specified, champions program structure, behavior change metrics
    decisions: []
    memory_updates: [Adoption targets (200-300 Y1, 10K+ Y3), champions program scale]
    approval: auto
    
  - id: phase-5
    name: ROI & Budget Framework
    agent: Rex + Yuty
    inputs: [All previous phases, Argy ROI research]
    outputs: [gap_roi_framework.md]
    quality_gate: 3-bucket model complete, 3-year investment model, CFO checklist validated, 5-minute pitch exists
    decisions: []
    memory_updates: [3-year investment ($7.2M-$7.8M), 3-year ROI (430-730%), failure cost ($60M-$120M/year)]
    approval: auto
    note: "[QUALITY GATE MISSED] ROI numbers conflict with Phase 3 — should have been caught here"
    
  - id: phase-6
    name: Risk & Governance
    agent: Anky + Rex
    inputs: [All previous phases, Argy risk research, retail AI failures]
    outputs: [gap_risk_governance.md]
    quality_gate: 5 risk categories defined, governance playbook with RACI, responsible AI principles, failure mode library, "no" framework
    decisions: []
    memory_updates: [Risk categories, escalation levels, governance maturity target]
    approval: auto
    
  - id: phase-7
    name: Executive Narrative
    agent: Yuty
    inputs: [All previous phases, MEMORY.md should exist but doesn't yet]
    outputs: [gap_executive_narrative.md]
    quality_gate: 6-page narrative, 5-minute pitch test passes, all numbers traceable to source
    decisions: []
    memory_updates: [Final canonical numbers for delivery]
    approval: human
    note: "[QUALITY GATE MISSED] ROI numbers from Phase 5 not reconciled — executive narrative uses different numbers"

workflow_metadata:
  total_phases: 8
  total_artifacts: 13
  parallelizable_phases: 2 (phase-1 partial, phase-3 full)
  one_way_door_decisions: 5
  quality_gates_missed: 2 (phase-5, phase-7)
  duration: 1 day (intensive)
  
lessons_learned:
  - MEMORY.md should have been created in Phase 0, not retroactively
  - Anky should have spot-checked between phases, not just at end
  - ROI number conflicts would have been caught with MEMORY.md canonical source
  - Phases 1 and 3 could have run 50% faster with parallel sub-agents
